# Generated by Django 4.1 on 2025-12-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatalogFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="파일명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("file", models.FileField(upload_to="catalog/", verbose_name="파일")),
                (
                    "file_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("image", "이미지"), ("other", "기타")],
                        default="other",
                        max_length=50,
                        verbose_name="파일 유형",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
            ],
            options={
                "verbose_name": "카탈로그 파일",
                "verbose_name_plural": "카탈로그 파일들",
                "ordering": ["-created_at"],
            },
        ),
    ]
