# Generated by Django 4.1.5 on 2025-12-13 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainpage", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
